import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from '@/components/Navbar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ar" dir="rtl">
      <body>
        <Navbar />
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}
